### ISSUE TITLE
Willing translators

### ISSUE THREAD

**Issue by venashial** [modrinth/translations#11]
(Transferred issue from [modrinth/knossos](https://github.com/modrinth/knossos/))

**Willing translators** (All help is welcome!)
- Korean: apersomany
- Russian: Brawaru, Felix14-v2
- Dutch: emielderckx

**Comment by Brawaru** [comment]
I think it's worth mention to others subscribed to the issue or just passing by that there is now a channel related to translations on [Modrinth Discord server](https://discord.gg/EUHuJHt). In there you can assign yourself a Translator role to be notified about new strings and updates related to internationalisation, as well as find per-language threads to connect with others speakers of your language to make collaboration easier.

**Comment by venashial** [comment]
We now have a project on [Crowdin](https://crowdin.com/project/modrinth)! I'm closing this issue as we now have both Discord and Crowdin to organize translations.
